version: "3.9"
services:
  mtg-app-db:
    image: postgres
    restart: always
    container_name: mtg-app-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: example
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres

volumes:
  postgres:
