-- AlterTable
ALTER TABLE "Card" ADD COLUMN     "arena_id" INTEGER,
ADD COLUMN     "art_cropImageURI" TEXT,
ADD COLUMN     "artist" TEXT,
ADD COLUMN     "booster" BOOLEAN,
ADD COLUMN     "border_color" TEXT,
ADD COLUMN     "border_cropImageURI" TEXT,
ADD COLUMN     "card_back_id" TEXT,
ADD COLUMN     "cardmarket_id" INTEGER,
ADD COLUMN     "cmc" INTEGER,
ADD COLUMN     "color_identity" TEXT[],
ADD COLUMN     "color_indicator" TEXT[],
ADD COLUMN     "colors" TEXT[],
ADD COLUMN     "content_warning" BOOLEAN,
ADD COLUMN     "digital" BOOLEAN,
ADD COLUMN     "edhrec_rank" INTEGER,
ADD COLUMN     "finishes" TEXT[],
ADD COLUMN     "flavor_name" TEXT,
ADD COLUMN     "flavor_text" TEXT,
ADD COLUMN     "frame" TEXT,
ADD COLUMN     "frame_effects" TEXT[],
ADD COLUMN     "full_art" BOOLEAN,
ADD COLUMN     "games" TEXT[],
ADD COLUMN     "hand_modifier" TEXT,
ADD COLUMN     "highres_image" BOOLEAN,
ADD COLUMN     "illustration_id" TEXT,
ADD COLUMN     "image_status" TEXT,
ADD COLUMN     "keywords" TEXT[],
ADD COLUMN     "lang" TEXT,
ADD COLUMN     "largeImageURI" TEXT,
ADD COLUMN     "layout" TEXT,
ADD COLUMN     "life_modifier" TEXT,
ADD COLUMN     "loyalty" TEXT,
ADD COLUMN     "mana_cost" TEXT,
ADD COLUMN     "mtgo_foil_id" INTEGER,
ADD COLUMN     "mtgo_id" INTEGER,
ADD COLUMN     "multiverse_ids" INTEGER[],
ADD COLUMN     "normalImageURI" TEXT,
ADD COLUMN     "oracle_id" TEXT,
ADD COLUMN     "oracle_text" TEXT,
ADD COLUMN     "oversized" BOOLEAN,
ADD COLUMN     "pngImageURI" TEXT,
ADD COLUMN     "power" TEXT,
ADD COLUMN     "printed_name" TEXT,
ADD COLUMN     "printed_text" TEXT,
ADD COLUMN     "printed_type_line" TEXT,
ADD COLUMN     "prints_search_uri" TEXT,
ADD COLUMN     "produced_mana" TEXT[],
ADD COLUMN     "promo" BOOLEAN,
ADD COLUMN     "promo_types" TEXT,
ADD COLUMN     "released_at" TEXT,
ADD COLUMN     "reprint" BOOLEAN,
ADD COLUMN     "reserved" BOOLEAN,
ADD COLUMN     "rulings_uri" TEXT,
ADD COLUMN     "scryfall_set_uri" TEXT,
ADD COLUMN     "scryfall_uri" TEXT,
ADD COLUMN     "security_stamp" TEXT[],
ADD COLUMN     "set" TEXT,
ADD COLUMN     "set_id" TEXT,
ADD COLUMN     "set_name" TEXT,
ADD COLUMN     "set_search_uri" TEXT,
ADD COLUMN     "set_type" TEXT,
ADD COLUMN     "set_uri" TEXT,
ADD COLUMN     "smallImageURI" TEXT,
ADD COLUMN     "story_spotlight" BOOLEAN,
ADD COLUMN     "tcgplayer_etched_id" INTEGER,
ADD COLUMN     "tcgplayer_id" INTEGER,
ADD COLUMN     "textless" BOOLEAN,
ADD COLUMN     "toughness" TEXT,
ADD COLUMN     "type_line" TEXT,
ADD COLUMN     "uri" TEXT,
ADD COLUMN     "variation" BOOLEAN,
ADD COLUMN     "variation_of" TEXT,
ADD COLUMN     "watermark" TEXT,
ALTER COLUMN "collectorNumber" SET DATA TYPE TEXT;

-- CreateTable
CREATE TABLE "CardFace" (
    "id" SERIAL NOT NULL,
    "artist" TEXT,
    "cmc" INTEGER,
    "color_indicator" TEXT,
    "colors" TEXT[],
    "flavor_text" TEXT,
    "illustration_id" TEXT,
    "smallImageURI" TEXT,
    "normalImageURI" TEXT,
    "largeImageURI" TEXT,
    "pngImageURI" TEXT,
    "art_cropImageURI" TEXT,
    "border_cropImageURI" TEXT,
    "layout" TEXT,
    "loyalty" TEXT,
    "mana_cost" TEXT,
    "name" TEXT NOT NULL,
    "oracle_id" TEXT,
    "oracle_text" TEXT,
    "power" TEXT,
    "printed_name" TEXT,
    "printed_text" TEXT,
    "printed_type_line" TEXT,
    "toughness" TEXT,
    "type_line" TEXT NOT NULL,
    "watermark" TEXT,
    "cardId" TEXT,
    "cardAlbumId" INTEGER,

    CONSTRAINT "CardFace_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "CardFace" ADD CONSTRAINT "CardFace_cardId_cardAlbumId_fkey" FOREIGN KEY ("cardId", "cardAlbumId") REFERENCES "Card"("id", "albumId") ON DELETE SET NULL ON UPDATE CASCADE;
