import * as Scry from "scryfall-sdk";

export interface Card {
  object: "card";
  arena_id?: number | null;
  id: string;
  lang: string;
  mtgo_id?: number | null;
  mtgo_foil_id?: number | null;
  multiverse_ids?: number[] | null;
  tcgplayer_id?: number | null;
  tcgplayer_etched_id?: number | null;
  cardmarket_id?: number | null;
  oracle_id: string;
  prints_search_uri: string;
  rulings_uri: string;
  scryfall_uri: string;
  uri: string;
  all_parts?: Scry.RelatedCard[] | null;
  card_faces: Scry.CardFace[];
  cmc: number;
  color_identity: Scry.Color[];
  color_indicator?: Scry.Color[] | null;
  colors?: Scry.Color[] | null;
  edhrec_rank?: number | null;
  hand_modifier?: Scry.Modifier | null;
  keywords: string[];
  layout: keyof typeof Scry.Layout;
  legalities: Scry.Legalities;
  life_modifier?: Scry.Modifier | null;
  loyalty?: string | null;
  mana_cost?: string | null;
  name: string;
  oracle_text?: string | null;
  oversized: boolean;
  power?: string | null;
  produced_mana?: Scry.Color[] | null;
  reserved: boolean;
  toughness?: string | null;
  type_line: string;
  artist?: string | null;
  booster: boolean;
  border_color: keyof typeof Scry.Border;
  card_back_id: string;
  collector_number: string;
  content_warning?: boolean | null;
  digital: boolean;
  finishes: (keyof typeof Scry.CardFinish)[];
  flavor_name?: string | null;
  flavor_text?: string | null;
  frame_effects?: (keyof typeof Scry.FrameEffect)[] | null;
  frame: keyof typeof Scry.CardFrame;
  full_art: boolean;
  games: (keyof typeof Scry.Game)[];
  highres_image: boolean;
  illustration_id?: string | null;
  image_status: keyof typeof Scry.CardStatus;
  image_uris?: Scry.ImageUris | null;
  prices: Scry.Prices;
  printed_name?: string | null;
  printed_text?: string | null;
  printed_type_line?: string | null;
  promo: boolean;
  promo_types?: (keyof typeof Scry.PromoType)[] | null;
  purchase_uris: Scry.PurchaseUris;
  rarity: keyof typeof Scry.Rarity;
  related_uris: Scry.RelatedUris;
  released_at: string;
  reprint: boolean;
  scryfall_set_uri: string;
  set_name: string;
  set_search_uri: string;
  set_type: Scry.Set["set_type"];
  set_uri: string;
  set: string;
  set_id: string;
  story_spotlight: boolean;
  textless: boolean;
  variation: boolean;
  variation_of?: string | null;
  security_stamp?: keyof typeof Scry.CardSecurityStamp | null;
  watermark?: string | null;
  preview?: Scry.Preview | null;
}
